### ISSUE TITLE
Incompatibility with certain builds of s2geometry

### ISSUE THREAD

**Issue by zklaus** [conda-forge/pys2index-feedstock#17]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The `s2geometry` changed the way it's built between versions 0.9.0, which produced *only* `libs2.so` and version 0.10.0, which produces `libs2.so`, `libs2.so.0`, and `libs2.so.0.10.0`, where the former two are links to the latter. This newer scheme is the more standard one, but there is a problem with the way that we are pinning. Currently, new versions of `pys2index` are built against `s2geometry >= 0.10.0`, but the `run` pin does not include that lower bound. Consequently, new versions of `pys2index` that link against `libs2.so.0` can end up in environments together with old versions of `s2geometry` that don't have that file.

As a short term solution, we should probably change the `run` pin here to `pin_compatible`. Longer term, it would be nice to split `s2geometry` into `libs2(geometry)` and `s2geometry`, where the former only has the library `libs2.so.0` and `libs2.so.0.10.0`, and the latter all the includes plus an appropriate run_export.

### Installed packages

```shell
-
```

### Environment info

```shell
-
```

**Comment by zklaus** [comment]
If we agree on this, we should probably also add a repodata patch to add the lower constraint for s2geometry to all pys2index builds for versions 0.1.3 and 0.1.4.

**Comment by benbovy** [comment]
> we should probably also add a repodata patch to add the lower constraint for s2geometry to all pys2index builds for versions 0.1.3 and 0.1.4.

That would certainly make things cleaner, although for this small package and no major version bump since it exists that is probably not very critical and recommend updating pys2index to the latest version may be enough. Unless there are many users who install other packages than pys2index that also depend on s2geometry?
